global:
  scrape_interval: 15s

scrape_configs:
  - job_name: jenkins-host
    static_configs:
      - targets: ["node-exporter:9100"]
        labels: { environment: lab }
  - job_name: containers
    static_configs:
      - targets: ["cadvisor:8080"]
        labels: { environment: lab }
